# Generated by Django 5.1.3 on 2024-12-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageEvent', '0002_club_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
