# Generated by Django 5.1.3 on 2024-12-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10),
        ),
    ]
